CREATE OR REPLACE VIEW NOTAS_COMPLETO_TREINAMENTO (
	CODIGO_NOTA,
	NOME_CLIENTE,
	VALOR_TOTAL
)
AS
SELECT  NE.IDCODNOTA AS CPDIGO_NOTA,
		CF.NOME AS NOME_CLIENTE,
		(NE.VALOR_TOTAL * 1.1) AS VALOR_TOTAL
FROM NOTASENTRADA NE, CLIFORNEC CF
WHERE NE.IDEMPRESA = CF.IDEMPRESA
AND NE.IDCLIFORNEC = CF.IDCLIFORNEC


///

CREATE SEQUENCE PESSOA_SEQ
		START WITH 5
		MAXVALUE 999999999
		MINVALUE 5
		INCREMENT 1
		NOCYCLE 
		NOORDER
		NOCACHE 	

///

SELECT  SUBSTR(NOME, 6, 5), --POSIÇÃO A PARTIR DO 6 - SUBSTR(NOME, LENGTH(NOME) - 5), --POSIÇÃO FINAL
		NOME,
		REPLACE(NOME, 'A', 'O') AS NOVO_NOME, --APENAS VISUAL - ALTERA DE A POR 0
		IDADE,
		ROUND(SALARIO,1), --ARREDONDAR AS CASAS DECIMAIS
		DECODE(IDCARGO, 1, 'ZÉ', 2, 'BOSS', 'SEM CARGO') AS CARGO
FROM PESSOA

///

